# Generated by Django 5.1 on 2024-09-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_selectedsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedsuggestion',
            name='user',
        ),
    ]
