# Generated by Django 5.1 on 2024-09-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_term_selectedsuggestion_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedsuggestion',
            name='user',
        ),
    ]
