# Generated by Django 5.1 on 2024-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_preferred_term_medicalterm_tree_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalterm',
            name='concept_id',
        ),
        migrations.AddField(
            model_name='medicalterm',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalterm',
            name='preferred_term',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
