# Generated by Django 5.1 on 2024-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_medicalterm_concept_id_medicalterm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicalterm',
            name='tree_number',
        ),
        migrations.AddField(
            model_name='medicalterm',
            name='concept_id',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
