# Generated by Django 5.1 on 2024-09-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_medicalterm_id_remove_medicalterm_tree_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalterm',
            old_name='preferred_term',
            new_name='tree_number',
        ),
    ]
