# Generated by Django 5.1 on 2024-09-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_preferred_term_medicalterm_tree_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalterm',
            old_name='concept_id',
            new_name='preferred_term',
        ),
    ]
