# Generated by Django 5.1 on 2024-09-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_concept_id_medicalterm_preferred_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalterm',
            old_name='tree_number',
            new_name='concept_id',
        ),
    ]
