# Generated by Django 5.1 on 2024-09-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_tree_number_medicalterm_concept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalterm',
            name='concept_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalterm',
            name='preferred_term',
            field=models.CharField(max_length=255),
        ),
    ]
